From Stdlib Require Import Bool List.
From compcert.common Require Import Values Memory.
From compcert.cfrontend Require Import Cop Clight.
From Guard Require Import AbstractGuard SemanticFacts ClightCondition
  ClightExprRewrite ClightExprRule ClightTreeRewrite.
Set Implicit Arguments.

Definition source_defined (a : expr) (s : clight_entry) : Prop :=
  exists v, eval_expr (entry_ge s) (entry_env s) (entry_temps s) (entry_memory s) a v.

(** The host justifies the entry domain from the source expression evaluation.
    A dimension, its executable tests, and a conditional equality proof form
    a plugin.  There is no global runtime assumption about all program states. *)
Record encoded_tree_rule (source candidate : expr) := EncodedTreeRule {
  rule_atoms : Type;
  rule_domain : clight_entry -> Prop;
  rule_dimension : property_dimension clight_entry rule_atoms rule_domain;
  rule_primitives : check_primitives decision_language rule_domain (decide_atom rule_dimension);
  rule_formula : formula rule_atoms;
  rule_type : typeof candidate = typeof source;
  rule_entry : forall s, source_defined source s -> rule_domain s;
  rule_local : forall s v,
    eval_expr (entry_ge s) (entry_env s) (entry_temps s) (entry_memory s) source v ->
    formula_property (atom_property rule_dimension) rule_formula s ->
    eval_expr (entry_ge s) (entry_env s) (entry_temps s) (entry_memory s) candidate v
}.

Definition generated_tree {source candidate} (r : encoded_tree_rule source candidate) :=
  synthesize_tree (rule_primitives r) (rule_formula r).

Theorem encoded_tree_rule_sound : forall source candidate
  (r : encoded_tree_rule source candidate),
  ClightTreeRewrite.expression_contract source (generated_tree r) candidate.
Proof.
  intros source candidate r. split; [exact (rule_type r)|].
  intros ge e le m v EV.
  assert (INV : rule_domain r (Entry ge e le m)).
  { apply rule_entry. exists v; exact EV. }
  exists (formula_accepts (decide_atom (rule_dimension r)) (rule_formula r) (Entry ge e le m)).
  split.
  - apply (proj2 (@synthesized_tree_correct (rule_atoms r) (rule_domain r)
      (decide_atom (rule_dimension r)) (rule_primitives r) (rule_formula r)
      (Entry ge e le m) _ INV)); reflexivity.
  - intro ACCEPT. eapply (rule_local r (Entry ge e le m) (v := v)); [exact EV|].
    eapply synthesized_tree_property; [exact INV|].
    apply (proj2 (@synthesized_tree_correct (rule_atoms r) (rule_domain r)
      (decide_atom (rule_dimension r)) (rule_primitives r) (rule_formula r)
      (Entry ge e le m) true INV)). symmetry; exact ACCEPT.
Qed.

(** Reuse previously certified rules without claiming that their guard was
    generated by the new property interface. *)
Lemma legacy_rule : forall a g c,
  ClightExprRewrite.expression_contract a g c ->
  ClightTreeRewrite.expression_contract a (Test g (Decision true) (Decision false)) c.
Proof.
  intros a g c [TYPE LOCAL]. split; auto.
  intros ge e le m v EV. destruct (LOCAL ge e le m v EV) as [vg [b [EG [BG ACCEPT]]]].
  exists b; split; auto. eapply run_test with (b := b).
  - exists vg; split; [exact EG|exact BG].
  - destruct b; constructor.
Qed.

Lemma lift_tree_binop_left : forall a g c op r ty,
  ClightTreeRewrite.expression_contract a g c ->
  ClightTreeRewrite.expression_contract (Ebinop op a r ty) g (Ebinop op c r ty).
Proof.
  intros a g c op r ty [TYPE CONTRACT]. split; [reflexivity|].
  intros ge e le m v EV. apply expression_binop_inv in EV.
  destruct EV as [vl [vr [EL [ER OP]]]].
  destruct (CONTRACT ge e le m vl EL) as [b [TREE LOCAL]].
  exists b; split; auto. intro ACCEPT.
  eapply eval_Ebinop; eauto. rewrite TYPE; exact OP.
Qed.

Lemma lift_tree_binop_right : forall a g c op l ty,
  ClightTreeRewrite.expression_contract a g c ->
  ClightTreeRewrite.expression_contract (Ebinop op l a ty) g (Ebinop op l c ty).
Proof.
  intros a g c op l ty [TYPE CONTRACT]. split; [reflexivity|].
  intros ge e le m v EV. apply expression_binop_inv in EV.
  destruct EV as [vl [vr [EL [ER OP]]]].
  destruct (CONTRACT ge e le m vr ER) as [b [TREE LOCAL]].
  exists b; split; auto. intro ACCEPT.
  eapply eval_Ebinop; eauto. rewrite TYPE; exact OP.
Qed.

Lemma lift_tree_unop : forall a g c op ty,
  ClightTreeRewrite.expression_contract a g c ->
  ClightTreeRewrite.expression_contract (Eunop op a ty) g (Eunop op c ty).
Proof.
  intros a g c op ty [TYPE CONTRACT]. split; [reflexivity|].
  intros ge e le m v EV. inversion EV; subst.
  - match goal with INNER : eval_expr _ _ _ _ a v1 |- _ =>
      destruct (CONTRACT ge e le m v1 INNER) as [b [TREE LOCAL]] end.
    exists b; split; auto. intro ACCEPT.
    eapply eval_Eunop; eauto. rewrite TYPE; assumption.
  - match goal with H : eval_lvalue _ _ _ _ (Eunop _ _ _) _ _ _ |- _ => inversion H end.
Qed.

Lemma lift_tree_cast : forall a g c ty,
  ClightTreeRewrite.expression_contract a g c ->
  ClightTreeRewrite.expression_contract (Ecast a ty) g (Ecast c ty).
Proof.
  intros a g c ty [TYPE CONTRACT]. split; [reflexivity|].
  intros ge e le m v EV. inversion EV; subst.
  - match goal with INNER : eval_expr _ _ _ _ a v1 |- _ =>
      destruct (CONTRACT ge e le m v1 INNER) as [b [TREE LOCAL]] end.
    exists b; split; auto. intro ACCEPT.
    eapply eval_Ecast; eauto. rewrite TYPE; assumption.
  - match goal with H : eval_lvalue _ _ _ _ (Ecast _ _) _ _ _ |- _ => inversion H end.
Qed.

Fixpoint select_tree_deep (select : expr -> option (decision_tree * expr)) (a : expr)
  : option (decision_tree * expr) :=
  match select a with
  | Some result => Some result
  | None => match a with
    | Ebinop op l r ty =>
        match select_tree_deep select l with
        | Some (g, c) => Some (g, Ebinop op c r ty)
        | None => match select_tree_deep select r with
                  | Some (g, c) => Some (g, Ebinop op l c ty) | None => None end
        end
    | Eunop op x ty => match select_tree_deep select x with
                      | Some (g, c) => Some (g, Eunop op c ty) | None => None end
    | Ecast x ty => match select_tree_deep select x with
                   | Some (g, c) => Some (g, Ecast c ty) | None => None end
    | _ => None
    end
  end.

Theorem select_tree_deep_sound : forall select,
  (forall a g c, select a = Some (g, c) -> ClightTreeRewrite.expression_contract a g c) ->
  forall a g c, select_tree_deep select a = Some (g, c) ->
    ClightTreeRewrite.expression_contract a g c.
Proof.
  intros select SOUND a; induction a; intros g c SEL;
    cbn [select_tree_deep] in SEL;
    destruct (select _) as [[g' c']|] eqn:ROOT;
    try solve [inversion SEL; subst; eapply SOUND; eauto]; try discriminate.
  - destruct (select_tree_deep select a) as [[gg cc]|] eqn:CHILD; try discriminate.
    inversion SEL; subst; apply lift_tree_unop; eauto.
  - destruct (select_tree_deep select a1) as [[gg cc]|] eqn:LEFT.
    + inversion SEL; subst; apply lift_tree_binop_left; eauto.
    + destruct (select_tree_deep select a2) as [[gg cc]|] eqn:RIGHT; try discriminate.
      inversion SEL; subst; apply lift_tree_binop_right; eauto.
  - destruct (select_tree_deep select a) as [[gg cc]|] eqn:CHILD; try discriminate.
    inversion SEL; subst; apply lift_tree_cast; eauto.
Qed.

Print Assumptions encoded_tree_rule_sound.
