From GuardMemory Require Import GuardMemoryWindowRuntimeFootprint GuardMemoryUnifiedCompiler.
From GuardAffineNest Require Import AffineNestSyntax AffineNestWords AffineNestExit AffineNestExamples.
From GuardAffineNest Require Import AffineNestSourceShape AffineNestFirstDomain.
From GuardAffineNest Require Import AffineNestLoopTrace.
From GuardAffineNest Require Import AffineNestControlTransfer.
From GuardAffineNest Require Import AffineNestShadowExit.
From GuardAffineNest Require Import AffineNestLoopEncoding AffineNestBoundEncoding AffineNestEncodingExamples.
From GuardAffineNest Require Import AffineNestMemoryProjection AffineNestLeafModel AffineNestFirstLeaf AffineNestUsedWords AffineNestLeafLoop.
From GuardAffineNest Require Import AffineNestLoopProjection AffineNestValuation AffineNestExpressionTail
  AffineNestMathDomain AffineNestSourceDecode AffineNestLeafDecode AffineNestRealDecode.
From GuardAffineNest Require Import AffineNestProfile AffineNestProfileSound AffineNestProfileExamples AffineNestBoundWords AffineNestGuardWords
  AffineNestProbeRenaming AffineNestProbe AffineNestProbeExecution AffineNestProbeStage AffineNestProbePartialExecution
  AffineNestProbeFrame AffineNestProbeInitialize AffineNestInitializedProbeFrame AffineNestGuardParameterCheck AffineNestGuardDomain
  AffineNestNumericGuard AffineNestNumericExecution AffineNestDomainGuard AffineNestAcceptedDomain AffineNestSourceGuard
  AffineNestNamespace AffineNestGuardPackage AffineNestPackageGuard AffineNestPackageExamples AffineNestPackageWords.
From GuardAffineNest Require Import AffineNestPackageDecode AffineNestSingleFootprint AffineNestPackageRanges
  AffineNestShadowTransport AffineNestCandidateLocal AffineNestRegion AffineNestStaticPackage AffineNestStaticExamples
  AffineNestCheckedCompiler AffineNestWholeCompiler AffineNestPropose AffineNestProposeExamples.
From GuardAffineNest Require Import AffineNestRangeProposal AffineNestRangeProposalExamples.
From GuardAffineNest Require Import AffineNestUnifiedCompiler.
From GuardAffineNest Require Import GuardedCandidateChoice AffineNestConditionedCompiler.
From GuardAffineNest Require Import AffineNestSiteSwap AffineNestSitePermutation AffineNestSiteChecker AffineNestBoundedSiteChecker.
From GuardAffineNest Require Import AffineNestDomainSplit AffineNestSplitChecker.
From GuardAffineNest Require Import AffineNestScanModel AffineNestScanPoints AffineNestScanSeparation
  AffineNestScanExecution AffineNestScanAll AffineNestMultiStaticPackage AffineNestPackageScanFootprint
  AffineNestMultiPresumption AffineNestMultiCandidateLocal AffineNestMultiGuardExecution AffineNestMultiRegion
  AffineNestMultiCheckedCompiler AffineNestMultiProposal.
Goal True. idtac "AFFINE_SYNTAX_BEGIN". exact I. Qed.
Print Assumptions affine_complement_test_value.
Print Assumptions affine_infer_axis_ranges.
Print Assumptions affine_infer_address_window.
Print Assumptions affine_source_range_proposal.
Print Assumptions affine_scan_result_points.
Print Assumptions affine_scan_points_exact.
Print Assumptions affine_scan_separation_sound.
Print Assumptions check_affine_multi_static_package.
Print Assumptions affine_reserve_multi_scans.
Print Assumptions first_checked_candidate_sound.
Print Assumptions inferred_three_level_ranges_accepted.
Print Assumptions overflowing_inferred_child_range_refused.
Print Assumptions invalid_configured_root_range_refused.
Print Assumptions actual_three_level_inferred_caps.
Print Assumptions affine_nest_shapes_check_sound.
Print Assumptions affine_nest_dependencies_check_sound.
Print Assumptions affine_root_expression_check_sound.
Print Assumptions affine_parameters_fresh_check_sound.
Print Assumptions check_affine_nest.
Print Assumptions affine_exit_temps_other.
Print Assumptions affine_nest_fresh_controls.
Print Assumptions three_affine_levels_recognized.
Print Assumptions forward_coordinate_dependency_refused.
Print Assumptions mismatched_bound_assignment_refused.
Print Assumptions mutated_parameter_registration_refused.
Print Assumptions three_level_exit_values.
Print Assumptions affine_nest_source_quiet.
Print Assumptions affine_nest_source_writes.
Print Assumptions affine_nest_body_writes.
Print Assumptions affine_nest_body_normal.
Print Assumptions affine_loop_expression_value.
Print Assumptions affine_lower_nest_axis.
Print Assumptions check_affine_bound_cap.
Print Assumptions three_level_loop_uses_real_prefixes.
Print Assumptions child_bounds_may_be_negative.
Print Assumptions grandchild_uses_both_levels_and_parameters.
Print Assumptions overflowing_bound_interval_refused.
Print Assumptions check_affine_leaf.
Print Assumptions affine_leaf_normal.
Print Assumptions affine_leaf_quiet.
Print Assumptions affine_leaf_writes.
Print Assumptions affine_first_child_frame.
Print Assumptions affine_leaf_arguments_value.
Print Assumptions affine_counted_memory_map_bounded.
Print Assumptions affine_word_view_frame.
Print Assumptions affine_word_view_update.
Print Assumptions affine_valuation_loop_environment.
Print Assumptions affine_loop_expression_tail_value.
Print Assumptions affine_math_domain.
Print Assumptions affine_checked_leaf_code.
Print Assumptions affine_checked_nest_loop.
Print Assumptions check_affine_nest_full.
Print Assumptions affine_checked_math_bound.
Print Assumptions checked_affine_profile_domain.
Print Assumptions three_level_signed_profile_accepted.
Print Assumptions insufficient_child_cap_refused.
Print Assumptions overflowing_child_bound_profile_refused.
Print Assumptions mismatched_leaf_box_refused.
Print Assumptions affine_first_headers_used_bound_word.
Print Assumptions affine_renamed_view_extend_set.
Print Assumptions affine_first_path_flag_exact.
Print Assumptions affine_probe_stage_child_view.
Print Assumptions affine_first_probe_writes.
Print Assumptions affine_root_probe_initial_view.
Print Assumptions check_affine_guard_parameters_sound.
Print Assumptions affine_register_domains_word_view.
Print Assumptions affine_register_domains_transport.
Print Assumptions affine_numeric_guard_sound.
Print Assumptions affine_numeric_guard_flag_frame.
Print Assumptions affine_domain_guard_accepted.
Print Assumptions check_affine_guard_namespace.
Print Assumptions check_affine_guard_package.
Print Assumptions real_three_level_memory_guard_package_accepted.
Print Assumptions public_result_scratch_refused.
Print Assumptions colliding_private_controls_refused.
Print Assumptions unallocated_private_controls_refused.
Print Assumptions affine_package_single_covered.
Print Assumptions affine_package_validator_within.
Print Assumptions affine_package_encoder_within.
Print Assumptions affine_shadow_source_writes.
Print Assumptions affine_statement_scope_check_sound.
Print Assumptions check_affine_static_package.
Print Assumptions real_three_level_static_package_accepted.
Print Assumptions missing_private_bound_declaration_refused.
Print Assumptions missing_guard_result_declaration_refused.
Print Assumptions affine_default_source_proposal.
Print Assumptions actual_source_default_proposal_accepted.
Goal True. idtac "AFFINE_BASELINE_BEGIN". exact I. Qed.
Print Assumptions window_source_runtime_domain.
Goal True. idtac "AFFINE_SOURCE_BEGIN". exact I. Qed.
Print Assumptions affine_partitioned_sources_execution.
Print Assumptions affine_child_setup_decode.
Print Assumptions affine_child_setup_read_words.
Print Assumptions affine_expression_word_value.
Print Assumptions affine_source_first_header_domain.
Print Assumptions affine_frontend_trace_decode.
Print Assumptions affine_frontend_trace_encode.
Print Assumptions affine_frontend_trace_last.
Print Assumptions affine_frontend_control_transfer.
Print Assumptions checked_affine_bound_exact.
Print Assumptions affine_frontend_memory_projection.
Print Assumptions affine_leaf_real_memory_decode.
Print Assumptions affine_source_first_leaf.
Print Assumptions affine_source_used_leaf_word.
Print Assumptions affine_leaf_sequence_semantics.
Print Assumptions affine_frontend_loop_projection.
Print Assumptions affine_bound_word_from_view.
Print Assumptions affine_nest_source_decode.
Print Assumptions affine_checked_leaf_decode.
Print Assumptions affine_checked_nest_source_decode.
Print Assumptions affine_source_guard_register_defined.
Print Assumptions affine_renamed_bound_evaluation.
Print Assumptions affine_probe_header_test.
Print Assumptions affine_first_probe_execution.
Print Assumptions affine_first_probe_partial_execution.
Print Assumptions affine_first_probe_public_frame.
Print Assumptions affine_initialized_first_probe_execution.
Print Assumptions affine_initialized_probe_public_frame.
Print Assumptions affine_source_guard_parameter_domains.
Print Assumptions affine_numeric_guard_encoding.
Print Assumptions affine_numeric_guard_execution.
Print Assumptions affine_domain_guard_execution.
Print Assumptions affine_source_domain_guard_execution.
Print Assumptions affine_package_guard_execution.
Print Assumptions affine_package_accepted_word_view.
Print Assumptions affine_package_root_words.
Print Assumptions affine_package_source_decode.
Print Assumptions affine_package_context_typed.
Print Assumptions affine_single_candidate_local.
Print Assumptions affine_guarded_region_sound.
Print Assumptions affine_scan_execution.
Print Assumptions affine_scan_all_execution.
Print Assumptions affine_package_scan_capabilities.
Print Assumptions affine_multi_guard_nonalias.
Print Assumptions affine_multi_candidate_local.
Print Assumptions affine_multi_guard_execution.
Print Assumptions affine_multi_guarded_region_sound.
Print Assumptions affine_site_swap_execution.
Print Assumptions affine_site_permutation_execution.
Goal True. idtac "AFFINE_EXIT_BEGIN". exact I. Qed.
Print Assumptions affine_exit_statement_execution.
Print Assumptions affine_source_shadow_exit.
Print Assumptions affine_checked_shadow_transport.
Goal True. idtac "AFFINE_CHECKED_BASELINE_BEGIN". exact I. Qed.
Print Assumptions check_memory_window_unified_region_sound.
Goal True. idtac "AFFINE_CHECKED_BEGIN". exact I. Qed.
Print Assumptions check_affine_region_sound.
Print Assumptions check_affine_multi_region_sound.
Print Assumptions validated_affine_site_domain_loops_at.
Print Assumptions checked_affine_bounded_site_candidate_correct.
Print Assumptions checked_affine_split_candidate_correct.
Print Assumptions check_conditioned_region_sound.
Print Assumptions checked_affine_regions_sound.
Goal True. idtac "AFFINE_WHOLE_BASELINE_BEGIN". exact I. Qed.
Print Assumptions compile_memory_unified_regions_correct.
Goal True. idtac "AFFINE_WHOLE_BEGIN". exact I. Qed.
Print Assumptions compile_affine_regions_correct.
Goal True. idtac "AFFINE_UNIFIED_BEGIN". exact I. Qed.
Print Assumptions compile_guardcert_correct.
Goal True. idtac "AFFINE_CONDITIONED_BEGIN". exact I. Qed.
Print Assumptions compile_guardcert_conditions_correct.
Goal True. idtac "AFFINE_AUDIT_END". exact I. Qed.
